POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "New Person",
  "number": "012-12-123123"
}

###
# Request with name missing should be rejected
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "",
  "number": "012-12-123123"
}

###
# Request with number missing should be rejected
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "New Person",
  "number": ""
}

###
# Request containing name that already exists in phonebook should be rejected
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "012-12-123123"
}

###
# Should not be able to add same person twice
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Duplicate Person",
  "number": "123-123-4444"
}

###
# Name less than 3 characters long should not be added
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "No",
  "number": "123-123-4444"
}

###
# Number less than 8 digits long should not be added
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Short Number",
  "number": "123"
}

###
# Number less than 8 digits  long should not be added even if string length > 8 characters
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Short Number",
  "number": "12-34-567"
}

###
GET http://localhost:3001/api/persons