POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Delete Me",
  "number": "012-12-123123"
}

###
DELETE http://localhost:3001/api/persons/1234

###
GET http://localhost:3001/api/persons